# Generated by Django 2.2.10 on 2020-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
    ]
