# Generated by Django 2.2.10 on 2020-07-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'Номер маршрута',
                'verbose_name_plural': 'Номера маршрутов ',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('routes', models.ManyToManyField(related_name='stations', to='app.Route', verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
    ]
