# Generated by Django 2.2.10 on 2020-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'К лету',
                'verbose_name_plural': 'К лету',
                'ordering': ['price'],
            },
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['price'], 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
    ]
