# Generated by Django 2.2.10 on 2020-07-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
