# Generated by Django 2.2.10 on 2020-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200722_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='summerwear',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
