# Generated by Django 2.2.10 on 2020-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200723_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='id сессии'),
        ),
    ]
