# Generated by Django 2.2.10 on 2020-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200727_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
