# Generated by Django 2.2.10 on 2020-06-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200617_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenTeacher',
            new_name='StudentTeacher',
        ),
    ]
