# Generated by Django 2.2.10 on 2020-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(match='“*\\.csv$', max_length=1000, path='C:\\coding\\Python_netology\\1.5_Django\\8._Create_and_support_app\\creating-project\\application', recursive=True, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Путь к файлу',
                'verbose_name_plural': 'Путь к файлу',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('number', models.PositiveIntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Колонка таблицы',
                'verbose_name_plural': 'Колонки таблицы',
            },
        ),
    ]
