# Generated by Django 2.2.10 on 2020-07-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='owner',
            new_name='master',
        ),
    ]
