# Generated by Django 2.2.10 on 2020-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200728_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
