# Generated by Django 2.2.10 on 2020-06-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200614_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleThematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Thematic_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('articles', models.ManyToManyField(through='articles.ArticleThematic', to='articles.Article')),
            ],
        ),
        migrations.AddField(
            model_name='articlethematic',
            name='thematic_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Thematic_section'),
        ),
    ]
