# Generated by Django 2.2.10 on 2020-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200614_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematic_section',
            name='articles',
            field=models.ManyToManyField(related_name='sections', through='articles.ArticleThematic', to='articles.Article'),
        ),
    ]
