# Generated by Django 2.2.10 on 2020-06-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200615_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlethematic',
            old_name='isMain',
            new_name='is_main',
        ),
    ]
