# Generated by Django 2.2.10 on 2020-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200616_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='relations', through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
