# Generated by Django 2.2.10 on 2020-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('system', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('pixel', models.IntegerField()),
                ('double_camera', models.BooleanField(default=False)),
                ('cpu', models.CharField(max_length=50)),
                ('screen', models.CharField(max_length=12)),
                ('fm', models.BooleanField(default=False)),
                ('additionally', models.TextField()),
            ],
        ),
    ]
