# Generated by Django 2.2.10 on 2020-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='model',
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=40),
        ),
    ]
