# Generated by Django 2.2.10 on 2020-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200610_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='additionally',
        ),
        migrations.AddField(
            model_name='phone',
            name='add',
            field=models.TextField(null=True),
        ),
    ]
