# Generated by Django 2.2.10 on 2020-06-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20200610_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='add',
            new_name='additionally',
        ),
    ]
