# Generated by Django 2.2.10 on 2020-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20200610_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='additionally',
            field=models.TextField(blank=True, null=True),
        ),
    ]
