# Generated by Django 2.2 on 2020-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20201228_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
