# Generated by Django 2.2 on 2020-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_auto_20201228_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
