# Generated by Django 2.2 on 2020-12-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_auto_20201228_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='release_date',
        ),
    ]
