# Generated by Django 2.2.7 on 2020-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200701_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
