# Generated by Django 2.2.10 on 2020-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200701_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
