# Generated by Django 2.2.10 on 2020-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='count',
            field=models.PositiveIntegerField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
