# Generated by Django 2.2.10 on 2020-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
